name = "SurfaceCoverage"
uuid = "75f4d65b-1b42-4905-9fb1-6d40607712e8"
authors = ["Vinod Janardhanan"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
